//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdeToFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPage
    {
        public int Id { get; set; }
        public string PageName { get; set; }
        public string Url { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
